### ISSUE TITLE
Update for Unity 5.6

### ISSUE THREAD

**Issue by bsy6766** [Elringus/SpriteGlow#3] opened 2017-05-11 20:01 UTC
Can you update shader code for Unity 5.6 please? 
Thanks.

**Comment by elringus** [comment] 2017-06-10 22:47
Hi, sorry for the late reply. 

There seems to be an issue in Unity 5.6 ([@issuetraacker](https://issuetracker.unity3d.com/issues/bloom-not-working-with-hdr-and-bloom-threshold-at-1?_ga=2.56462315.1588034897.1496704676-28796645.1477174609)) which makes it impossible for the effect to work (it relies on the HDR sprite 'mask' and bloom threshold > 1). 

I've commited some improvements and fixes to the [2.0 branch](https://github.com/Elringus/SpriteGlow/tree/2.0-(Unity-5.6)), but guess I'll wait for them to fix the issue before pushing it to the master.

**Comment by elringus** [comment] 2017-06-12 22:58
Seems like the issue is now resolved with the latest Unity patch.

**Closed as completed by elringus** 2017-06-12 22:58 UTC
