### ISSUE TITLE
i dont know how to fix

### ISSUE THREAD

**Issue by stickylabdev** [Elringus/SpriteGlow#23] opened 2018-03-20 03:15 UTC
![screenshot_63](https://user-images.githubusercontent.com/13078369/37634088-9ee05c50-2c27-11e8-8b74-4874705be587.png)

**Comment by Elringus** [comment] 2018-03-20 10:44
Take a look at: https://github.com/Elringus/SpriteGlow/issues/22

**Comment by elringus** [comment] 2018-03-20 10:45
Duplicate of #22

**Closed as completed by elringus** 2018-03-20 10:45 UTC
Labels: duplicate

**Comment by stickylabdev** [comment] 2018-03-20 10:50
is this really work on android ?

**Comment by elringus** [comment] 2018-03-20 10:54
Well, it should work on any platform with SM2.0 and HDR support. Performance will vary depending on the bloom solution, though. It worked fine on my xperia android tablet.
